authors:
  alexandre_cavalie:
      name: Alexandre Cavalié
      web: https://twitter.com/alexcavalie
  hugo_bosse:
      name: Hugo Bosse
      web: https://twitter.com/hugoPYNOTS

markdown: rdiscount
permalink: /:title.html
destination: ../../public/blog
auto: true
exclude:
  - Rakefile
  - Gemfile
  - .gitignore

