authors:
  alexandre_cavalie:
      name: Alexandre Cavalié
      web: https://twitter.com/alexcavalie
  hugo_bosse:
      name: Hugo Bosse
      web: https://twitter.com/hugoPYNOTS

markdown: rdiscount
permalink: /:title
destination: ../../app/views/blog

auto: true
exclude:
  - Rakefile
  - Gemfile
  - .gitignore

